#!/bin/bash

cd /usr/local/hadoop/etc/hadoop/
hadoop jar camus-example-0.1.0-SNAPSHOT-shaded.jar com.linkedin.camus.etl.kafka.CamusJob -P /usr/local/camus/camus-example/src/main/resources/camus.properties



# You can black-list and white-list topics by specifying topic names in the following two lines in the /usr/local/camus/camus-example/src/main/resources/camus.properties file

#kafka.blacklist.topics=blacklist-topic1,blacklist-topic2
#kafka.whitelist.topics=whitelist-topic1,whitelist-topic2
